services:
  - type: web
    name: skribble-backend
    env: node 
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 8080

  - type: web
    name: skribble-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          type: web
          name: skribble-backend
          envVarKey: RENDER_EXTERNAL_URL
